### ISSUE TITLE
(Often) After logging in a coach with active sessions typically sees none and has to go through the Team flow before any appear

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#467]
### to reproduce this:
1. Select a team with regular attendance type,  a roster of students and at least three sessions two weeks apart
2. set the user Profile>Calendar Option to M=Month
3. Switch to Sessions View
4. Verify the month is selected on the calendar where a session should appear
5. Pull down to refresh (to be sure of a load)
6. Switch to the Team View
7. Select the team being used for testing
8. Observe the list of Team Sessions that appear
RESULT:
The lists do not match. The Sessions View may include one or two but not all teams or sessions that are connected to that user.
Tested with
LautiTestCoach
Yuri Morales

Expectation:
 The Sessions View should show ALL of the sessions with that coach assigned in any role that is within the selected date range. This should happen by default without requiring a refresh the first time, at least. And should populate fully if the dates are changed.

**Comment by CritiqalPete** [comment]
@za-zohaib please review this. Is it clear how we can move the update of the Sessions data to a place where the screen is populated with current Sessions and not have to interact with the Calendar first?

**Comment by za-zohaib** [comment]
Hi @CritiqalPete what i understood from this is that we shouldnot need to pull down and refresh the screen to show correct session. As i have tried this with sessions and team sessions screen both works fine if we pull down and refresh the screen. Do let me know if you want anything else. Thanks

**Comment by za-zohaib** [comment]
@CritiqalPete one more thing i noticed is that when we sign in the default date range on calendar is one week previous and one week ahead from today. e.g if today is 16 may 24 the date range on calendar will be 9 may 24 - 23 may 24. And if we change the selection on  Profile>Calendar Option to M/W/T it works on both session and teams page after refresh ( pull down ). There are two questions i have here

- First. This M/W/T selection from Profile is discared if user logs out and logs back in. After loging back in the default 1 week before and 1 week after range is shown. Is this desired behaviour?

- Second. If a user has selected default M/W/T from his Profile then after coming to teams or sesions screen he sees the selected default after refresh but if he manually change the date range again then what should happen with the selected default from Profile because if he refresh the screen that Profile default is applied rather then the one he selected manually from date range.

- Thridly. Do we need to share the manually selected date range from calendar accross the tabs ( Sessions and Teams ) to show the same result.

Do let me know if there is any confusion we can have a chat and discuss. Thanks

**Comment by za-zohaib** [comment]
@CritiqalPete  one more thing i noticed

- when user is logged in after loggin out (in profile screen M/W/T is not selected) and by default for **_Sessions Tab_** in calender date range
if today is 05/16/24 the date range on calendar will be from 05/09/16 - 05/23/24) is **_2 weeks_** similarly for **_Teams Tab_** (remeber in profile screen M/W/T is still not selected) in calender date range is **_3 weeks_** (if today is 05/16/24 the date range on calendar will be from 05/02/16 - 05/23/24). 

and if we select M/W/T from profile screen then that date range will be shown on refresh on both Tabs.



 Is this desired behaviour ? 2 weeks range for  **_Sessions Tab_** and 3 weeks for **_Teams Tab_**   or both Tabs should have same date range ?? 

Do let me know if there is any confusion we can have a chat and discuss. Thanks .

**Comment by za-zohaib** [comment]
@CritiqalPete wanted to know if you were able to look at above questions.

**Comment by CritiqalPete** [comment]
### Responses to previous UX questions:
1. when a user completed an operation that potentially changes what will be seen on the Sessions view (e.g. add/edit a session) the app should do the refresh for them automatically
2. in some cases we have seen: a blank session screen (based on an empty date range), add a session in that range, pull-refresh and the view stays blank, suggesting there was an incomplete transaction or error.
### Requested Changes:
- analytics for when the view is refreshed that have additional parameters: Min_Date, Max_Date, RowCount (number of records displayed)
- analytics for session create/edit includes session_date so we can determine if it should appear in the view
- if the view is empty and the recently updated session record is outside the date range, a message: The session you updated will not appear with the present date range. Tap [**Include Recent**] to expand the range to include this session.

### Comments:
_An empty session screen should be very very rare for typical everyday coach usage. I expanded the default days on the calendar to reduce this but the app simply needs to be smarter and I would like the Design Team to explore "1-tap" solutions to emphasize TODAY, THIS WEEK, THIS MONTH, especially as an alternative to a blank screen.

**Comment by za-zohaib** [comment]
@CritiqalPete above Request changes sounds good. One question I have i that where should we put [include Recent] button.

**Comment by CritiqalPete** [comment]
since it's only seen periodically and in the context of an empty view (where a list of Sessions is expected) let's try putting it front and center on that view, above the [+ADD SESSION] Button.

**Comment by CritiqalPete** [comment]
Date Range Defaults: Let's align on 2 weeks before and after {Today} when the date filter has not been set but let's make that a Global Tunable Parameter which may added in the user Profile options when we have time

**Comment by CritiqalPete** [comment]
reviewed and tested all the basic flows. Let's merge!

**Comment by za-zohaib** [comment]
@CritiqalPete how will we know the recent included session? If a user has not added any session lets say for one month?

**Comment by za-zohaib** [comment]
Secondly one question got unanswered from above

If a user has selected default M/W/T from his Profile then after coming to teams or sesions screen he sees the date range according to his selected default after refresh but if he manually change the date range again then what should happen with the selected default from Profile because if he refresh the screen that Profile default date range is applied rather then the one he selected manually from date range.

**Comment by CritiqalPete** [comment]
@za-zohaib I want to close this now but it gives me an idea. How about a little widget on the Sessions view to let the user toggle between a Month/Week/Day filter? I will make a ticket.
